// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc1
// source: src/proto/product-service.proto

package products

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_src_proto_product_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_product_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_src_proto_product_service_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ProductId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductId) Reset() {
	*x = ProductId{}
	mi := &file_src_proto_product_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductId) ProtoMessage() {}

func (x *ProductId) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_product_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductId.ProtoReflect.Descriptor instead.
func (*ProductId) Descriptor() ([]byte, []int) {
	return file_src_proto_product_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProductId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProductList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	mi := &file_src_proto_product_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_product_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_src_proto_product_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProductList) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_src_proto_product_service_proto protoreflect.FileDescriptor

const file_src_proto_product_service_proto_rawDesc = "" +
	"\n" +
	"\x1fsrc/proto/product-service.proto\x12\aproduct\x1a\x1bgoogle/protobuf/empty.proto\"\x81\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\"\x1b\n" +
	"\tProductId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\";\n" +
	"\vProductList\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts2\x8d\x02\n" +
	"\x0eProductService\x12,\n" +
	"\x06Create\x12\x10.product.Product\x1a\x10.product.Product\x127\n" +
	"\aFindAll\x12\x16.google.protobuf.Empty\x1a\x14.product.ProductList\x120\n" +
	"\bFindById\x12\x12.product.ProductId\x1a\x10.product.Product\x12,\n" +
	"\x06Update\x12\x10.product.Product\x1a\x10.product.Product\x124\n" +
	"\x06Delete\x12\x12.product.ProductId\x1a\x16.google.protobuf.EmptyB\x13Z\x11./src/pb/productsb\x06proto3"

var (
	file_src_proto_product_service_proto_rawDescOnce sync.Once
	file_src_proto_product_service_proto_rawDescData []byte
)

func file_src_proto_product_service_proto_rawDescGZIP() []byte {
	file_src_proto_product_service_proto_rawDescOnce.Do(func() {
		file_src_proto_product_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_product_service_proto_rawDesc), len(file_src_proto_product_service_proto_rawDesc)))
	})
	return file_src_proto_product_service_proto_rawDescData
}

var file_src_proto_product_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_proto_product_service_proto_goTypes = []any{
	(*Product)(nil),       // 0: product.Product
	(*ProductId)(nil),     // 1: product.ProductId
	(*ProductList)(nil),   // 2: product.ProductList
	(*emptypb.Empty)(nil), // 3: google.protobuf.Empty
}
var file_src_proto_product_service_proto_depIdxs = []int32{
	0, // 0: product.ProductList.products:type_name -> product.Product
	0, // 1: product.ProductService.Create:input_type -> product.Product
	3, // 2: product.ProductService.FindAll:input_type -> google.protobuf.Empty
	1, // 3: product.ProductService.FindById:input_type -> product.ProductId
	0, // 4: product.ProductService.Update:input_type -> product.Product
	1, // 5: product.ProductService.Delete:input_type -> product.ProductId
	0, // 6: product.ProductService.Create:output_type -> product.Product
	2, // 7: product.ProductService.FindAll:output_type -> product.ProductList
	0, // 8: product.ProductService.FindById:output_type -> product.Product
	0, // 9: product.ProductService.Update:output_type -> product.Product
	3, // 10: product.ProductService.Delete:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_proto_product_service_proto_init() }
func file_src_proto_product_service_proto_init() {
	if File_src_proto_product_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_product_service_proto_rawDesc), len(file_src_proto_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_product_service_proto_goTypes,
		DependencyIndexes: file_src_proto_product_service_proto_depIdxs,
		MessageInfos:      file_src_proto_product_service_proto_msgTypes,
	}.Build()
	File_src_proto_product_service_proto = out.File
	file_src_proto_product_service_proto_goTypes = nil
	file_src_proto_product_service_proto_depIdxs = nil
}
